### ISSUE TITLE
Game Header

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#3]
**AS A** Logged user

**I WANT TO** See at the top of the page an header where I can see:
-  my username
- logout button
- some link/button to [pepper app](https://app.peppergaming.com) where I can see my assets

**SO THAT** I can clearly know that I am logged and have some way to reach the pepper app

**TASKS**:

- [x] Design
- [x] Implementation
- [ ] CSS

**Comment by AndreaRavano** [comment]
![Starbattle header](https://user-images.githubusercontent.com/18379363/181264234-31d6ee6f-7f8c-4614-99e0-e98f60f7923e.png)
![Starbattle header open](https://user-images.githubusercontent.com/18379363/181264240-ac4056b3-c3b5-4c2e-b344-830b2dc46db4.png)
