### ISSUE TITLE
Game Page - Start view

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#4]
**AS A** Logged User

**I WANT TO** See in the Game Page a _Start View_ with instructions, start button and starship chooser

**SO THAT** I can:
-  see instructions about how to play 
- a chooser of available starships (basic one and my NFTs)

**TASKS**
- [x] Design
- [x] Implementation

**Comment by AndreaRavano** [comment]
To keep it as simple as possible, i would remove the how-to-play instruction, arrow + spacebar, mega-standard.

![Starbattle intro - logged](https://user-images.githubusercontent.com/18379363/181269553-34e7e02b-d456-4f7b-8a8a-c865c816d6d2.png)
