### ISSUE TITLE
Game Page - Game View

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#5]
**AS A** Logged User

**I WANT TO** Play the game right after I click start in the Game Page Start View

**SO THAT** I can enjoy the game with the settings I previously chose

Original game codebase: https://github.com/CodingWith-Adam/space-invaders

**Comment by ggxforce** [comment]
https://medium.com/@pdx.lucasm/canvas-with-react-js-32e133c05258
