### ISSUE TITLE
Enable enhanced game features for NFT starships

### ISSUE THREAD

**Issue by cardosofelipe** [peppergaming/pepper-star-battle#9]
**AS A** User

**I WANT TO** Have enhanced features (double shots, shields, etc) in game, if I am using an NFT starship

**SO THAT** I can enjoy the benefits of my NFTs

**TASKS**:

- [x] Design: 
- enhancements
- new graphic assets @AndreaRavano 
- [x] Wire NFTs metadata to in-game enhancements

**Comment by AndreaRavano** [comment]
We have decided to include in the first demo this NFT attributes with relative features:

- Weapon: 
    - single shot (standard)
    - double shot
    - laser
 - Engine: 
    - low (standard)
    - high
    - giga
 
Different Graphics for weapon types should be rendered directly on canvas, while for engine are included with the starship png assets
